### ISSUE TITLE
Implementing features into upstream

### ISSUE THREAD

**Issue by SoCuul** [vlourme/BHInsta#2]
Hi! Would it be okay if I implemented some of your features into the upstream branch?

**Comment by vlourme** [comment]
Hello, no problem! Maybe we could collaborate on your repository as it is much cleaner. Or I can sync with your repository and do a PR if you prefer. I will take some time during this weekend to rework my BHInsta fork using yours.

I am also working on an updated version of RedditFilter is you are interested! (much harder than Instagram tweak imo)

**Comment by SoCuul** [comment]
I'll try to push my changes later today, as I've restructured stuff a little bit.

Also I've already started working on the focus mode features!

**Comment by SoCuul** [comment]
If you check the upstream repo, you can probably see how many things have changed since the previous version haha.
Should be pretty stable from now-on though.

**Comment by vlourme** [comment]
Well done. I think I will rebase this repo based on your fork and add my some of my features (such as "hide every post" and "hide explore posts").

**Comment by vlourme** [comment]
This is done, a PR is available on your repo.
I will continue to sync this repo with yours and release IPA files.
