### ISSUE TITLE
IPA possible copyright issues

### ISSUE THREAD

**Issue by SoCuul** [vlourme/BHInsta#5]
Hey!

Companies are starting to come after tweak repos that distribute IPAs, so you might want to remove them before they DMCA the entire repo.

https://www.reddit.com/r/jailbreak/comments/1b86tiz/balackburn_here_maintainer_of_ytliteplus_ive_just/
https://enterprise.githubsupport.com/attachments/token/1u4kyYJnjA8HZTPMXOGBhRk4Q/?name=2024-03-06-google.rtf

**Comment by vlourme** [comment]
Hey, thank you for the reminder. I was already aware of this Reddit post. Hopefully, Instagram does not start doing the same. For now, I will continue to publish the IPA, if someday I receive a DMCA notice, then I will just delete IPAs from releases and provide a building guide or try to create an online infrastructure like opa334 mentioned (or GitHub actions like YYLitePlus did).
